name: Generate JSON and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git merge master
          yarn install
          node build.js
          git config --global user.email "xxx@xxx.xxx"
          git config --global user.name "XXX XXX"
          git add .
          git commit -m "rebuilt"
          git push origin gh-pages --force
