name: Generate JSON and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - run: |
          git checkout gh-pages
          yarn install
          node build.js
          git push origin gh-pages
